config/routes.rb
Coffeebalance::Application.routes.draw do
  resources :coffee_types
  resources :appointments
  
  get "appointments/by_user/current", to: "appointments#by_current_user"
  post "appointments/by_user/plus/:coffee_type_id", to: "appointments#plus_one_by_current_user"
  post "appointments/by_user/minus/:coffee_type_id", to: "appointments#minus_one_by_current_user"

  get "home/index"
  devise_for :users
  root :to => "home#index"

end

app/models/appointment.rb
# Table Appointments
# Columns
# => coffee_type_id
# => user_id
# => amount
class Appointment < ActiveRecord::Base
  # Relationships
	belongs_to :coffee_type
	belongs_to :user
	
	validates_presence_of :coffee_type_id
	validates_presence_of :user_id
	validates_numericality_of :amount, :only_integer => true, :allow_nil => false
end

app/models/coffee_type.rb
class CoffeeType < ActiveRecord::Base
   has_many :appointments, dependent: :destroy
   has_many :users, through: :appointments
   
   validates_presence_of :name
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :authentication_keys => [:login]

  has_many :appointments, dependent: :destroy
  has_many :coffee_types, through: :appointments

  attr_accessor :login
  def login=(login)
    @login = login
  end

  def login
    @login || self.username || self.email
  end

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions).first
    end
  end

  validates :username,
  :uniqueness => {
    :case_sensitive => false
  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
  end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_appointment, only: [:show, :edit, :update, :destroy]

  # GET /appointments
  # GET /appointments.json
  def index
    @total = Appointment.count
    @page = params["page"]  ? params["page"] : 1
    @appointments = Appointment.paginate(:page => @page)
    @pages = (@total.to_f / WillPaginate.per_page).ceil
  end
  
  # GET /appointments/by_user/current
  # GET /appointments/by_user/current.json
  def by_current_user
    @total = Appointment.where(user_id: current_user.id).count
    @page = params["page"]  ? params["page"] : 1
    @appointments = Appointment.where(user_id: current_user.id).paginate(:page => @page)
    @pages = (@total.to_f / WillPaginate.per_page).ceil
    render "index"
  end
  
  # GET /appointments/by_user/plus/1
  # GET /appointments/by_user/plus/1.json
  def plus_one_by_current_user
    do_appointment(1)
  end
  
  # GET /appointments/by_user/minus/1
  # GET /appointments/by_user/minus/1.json
  def minus_one_by_current_user
    do_appointment(-1)
  end
  
  # Helper method for minus_one_by_user and plus_one_by_user
  def do_appointment(amount_param)
    appointment = Appointment.new({:coffee_type_id => params[:coffee_type_id], :user_id => current_user.id, :amount => amount_param})
    if appointment.save
      render :text => Appointment.where("coffee_type_id = ? and user_id = ?", params[:coffee_type_id], current_user.id).sum(:amount), :status => 200, :content_type => "plain/text"
    else
      render :nothing => true, :status => 500, :content_type => "plain/text"
    end
  end

  # GET /appointments/1
  # GET /appointments/1.json
  def show
  end

  # GET /appointments/new
  def new
    @appointment = Appointment.new
  end

  # GET /appointments/1/edit
  def edit
  end

  # POST /appointments
  # POST /appointments.json
  def create
    @appointment = Appointment.new(appointment_params)

    respond_to do |format|
      if @appointment.save
        format.html { redirect_to @appointment, notice: 'Appointment was successfully created.' }
        format.json { render action: 'show', status: :created, location: @appointment }
      else
        format.html { render action: 'new' }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appointments/1
  # PATCH/PUT /appointments/1.json
  def update
    respond_to do |format|
      if @appointment.update(appointment_params)
        format.html { redirect_to @appointment, notice: 'Appointment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointments/1
  # DELETE /appointments/1.json
  def destroy
    @appointment.destroy
    respond_to do |format|
      format.html { redirect_to appointments_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def appointment_params
      params.require(:appointment).permit(:coffee_type_id, :user_id, :amount)
    end
end

app/controllers/coffee_types_controller.rb
class CoffeeTypesController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_coffee_type, only: [:show, :edit, :update, :destroy]

  # GET /coffee_types
  # GET /coffee_types.json
  def index
    @coffee_types = CoffeeType.all
  end

  # GET /coffee_types/1
  # GET /coffee_types/1.json
  def show
  end

  # GET /coffee_types/new
  def new
    @coffee_type = CoffeeType.new
  end

  # GET /coffee_types/1/edit
  def edit
  end

  # POST /coffee_types
  # POST /coffee_types.json
  def create
    @coffee_type = CoffeeType.new(coffee_type_params)

    respond_to do |format|
      if @coffee_type.save
        format.html { redirect_to @coffee_type, notice: 'Coffee type was successfully created.' }
        format.json { render action: 'show', status: :created, location: @coffee_type }
      else
        format.html { render action: 'new' }
        format.json { render json: @coffee_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coffee_types/1
  # PATCH/PUT /coffee_types/1.json
  def update
    respond_to do |format|
      if @coffee_type.update(coffee_type_params)
        format.html { redirect_to @coffee_type, notice: 'Coffee type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @coffee_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coffee_types/1
  # DELETE /coffee_types/1.json
  def destroy
    @coffee_type.destroy
    respond_to do |format|
      format.html { redirect_to coffee_types_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coffee_type
      @coffee_type = CoffeeType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def coffee_type_params
      params.require(:coffee_type).permit(:name)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate_user!

  def index
    @coffee_balances = CoffeeType.joins("left outer join appointments on coffee_types.id = appointments.coffee_type_id and appointments.user_id = " + current_user.id.to_s).group("coffee_types.id").sum("appointments.amount")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/coffee_types_helper.rb
module CoffeeTypesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/appointments/_form.html.erb
<%= form_for(@appointment, :html => {"data-abide" => ""}) do |f| %>
  <% if @appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

      <ul>
      <% @appointment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :coffee_type_id %>
    <%= collection_select(:appointment, :coffee_type_id, CoffeeType.all, :id, :name, :prompt => "Select coffee type...", :required => true) %>
    <small class="error">Coffee type is required. Select a coffee type.</small>
  </div>
  
  <!-- The current user is the appointment owner -->
  <%= f.hidden_field :user_id, :value => current_user.id %>

  <div class="field">
  	<%= f.label :amount %>
  	<%= f.number_field :amount, required: true %>
  	<small class="error">Amount is required. Enter an integer value.</small>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/appointments/edit.html.erb
<h1>Editing appointment</h1>

<%= render 'form' %>

<%= link_to 'Show', @appointment %> |
<%= link_to 'Back', appointments_path %>

app/views/appointments/index.html.erb
<div class="row">

	<div class="large-12 columns">
		<h1 class="text-center">Listing appointments</h1>

		<table class="full_width">
		  <thead>
		    <tr>
		      <th>Coffee type</th>
		      <th>User</th>
		      <th>Amount</th>
		      <th class="action_column"></th>
		      <th class="action_column"></th>
		      <th class="action_column"></th>
		    </tr>
		  </thead>
		
		  <tbody>
		    <% @appointments.each do |appointment| %>
		      <tr>
		      	<td><%= appointment.coffee_type.name %></td>
		      	<td><%= appointment.user.username %></td>
		      	<td><%= appointment.amount %></td>
		        <td class="action_column"><%= link_to 'Show', appointment %></td>
		        <td class="action_column"><%= link_to 'Edit', edit_appointment_path(appointment) %></td>
		        <td class="action_column"><%= link_to 'Destroy', appointment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
		      </tr>
		    <% end %>
		  </tbody>
		</table>
		<br>

		<div class="pagination-centered">
			<ul class="pagination">
				<% if @pages > 0 %>
					<% @pages.times do |i| %>
						<%= content_tag :li, class: @page.to_i == (i + 1).to_i ? "current" : ""  do -%>
							<a href="<%= request.fullpath.split("?")[0] %>?page=<%= i + 1 %>"><%= i + 1 %></a>
						<% end %>
					<% end %>
				<% else %>
					<li class="current"><a href="javascript:void(0)">1</a></li>
				<% end %>
			</ul>
		</div>
		<br>

		<%= link_to 'New Appointment', new_appointment_path %>

	</div>
</div>

app/views/appointments/new.html.erb
<div class="row">
	<div class="large-6 large-centered columns">
		<h1>New appointment</h1>

		<%= render 'form' %>

		<%= link_to 'Back', appointments_path %>
	</div>
</div>

app/views/appointments/show.html.erb
<div class="row">
	<div class="large-6 large-centered columns">
		<p id="notice"><%= notice %></p>

		<p>
  			<strong>Coffee type:</strong>
  			<%= @appointment.coffee_type.name %>
		</p>
		<p>
  			<strong>Owner:</strong>
  			<%= @appointment.user.login %>
		</p>
		<p>
  			<strong>Amount:</strong>
  			<%= @appointment.amount %>
		</p>

		<%= link_to 'Edit', edit_appointment_path(@appointment) %> |
		<%= link_to 'Back', appointments_path %>
	</div>
</div>

app/views/coffee_types/_form.html.erb
<%= form_for(@coffee_type, :html => {"data-abide" => ""}) do |f| %>
  <% if @coffee_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@coffee_type.errors.count, "error") %> prohibited this coffee_type from being saved:</h2>

      <ul>
      <% @coffee_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, :required => true %>
    <small class="error">Name is required and must not be empty.</small>
  </div>
  <div class="actions">
    <%= f.submit "Save" %>
  </div>
<% end %>

app/views/coffee_types/edit.html.erb
<h1>Editing coffee_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @coffee_type %> |
<%= link_to 'Back', coffee_types_path %>

app/views/coffee_types/index.html.erb
<div class="row">
	<div class="large-12 large-centered columns">
		<h1 class="text-center">Listing Coffee Types</h1>

		<table class="full_width">
		  <thead>
		    <tr>
		      <th>Name</th>
		      <th class="action_column"></th>
		      <th class="action_column"></th>
		      <th class="action_column"></th>
		    </tr>
		  </thead>

		  <tbody>
		    <% @coffee_types.each do |coffee_type| %>
		      <tr>
		        <td><%= coffee_type.name %></td>
		        <td class="action_column"><%= link_to 'Show', coffee_type %></td>
		        <td class="action_column"><%= link_to 'Edit', edit_coffee_type_path(coffee_type) %></td>
		        <td class="action_column"><%= link_to 'Destroy', coffee_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
		      </tr>
		    <% end %>
		  </tbody>
		</table>

		<br>

		<%= link_to 'New Coffee type', new_coffee_type_path %>
	</div>
</div>

app/views/coffee_types/new.html.erb
<div class="row">
	<div class="large-6 large-centered columns">
		<h1>New Coffee Type</h1>

		<%= render 'form' %>

		<%= link_to 'Back', coffee_types_path %>
	</div>
</div>

app/views/coffee_types/show.html.erb
<div class="row">
	<div class="large-6 large-centered columns">
		<p id="notice"><%= notice %></p>

		<p>
  			<strong>Name:</strong>
  			<%= @coffee_type.name %>
		</p>

		<%= link_to 'Edit', edit_coffee_type_path(@coffee_type) %> |
		<%= link_to 'Back', coffee_types_path %>
	</div>
</div>

app/views/home/index.html.erb
<br />
<br />
<div class="row">
	<div class="large-12 large-centered columns">
		<h1 class="text-center">My Coffee Balance</h1>

		<table class="full_width">
		  <thead>
		    <tr>
		      <th>Coffee type</th>
		      <th>Balance</th>
		      <th class="action_column_large">Actions</th>
		    </tr>
		  </thead>

		  <tbody>
		    <% @coffee_balances.each do |coffee_balance| %>
		      <tr>
		        <td><%= CoffeeType.find(coffee_balance[0]).name %></td>
		        <td class="right"><%= coffee_balance[1] %></td>
		        <td class="action_column_large">
		        	<span class="btn_plus action_image" data-coffee-type-id="<%= coffee_balance[0] %>"><%= image_tag "ic_plus.png" %></span>
		        	<span class="btn_minus action_image" data-coffee-type-id="<%= coffee_balance[0] %>"><%= image_tag "ic_minus.png" %></span>
		        </td>
		      </tr>
		    <% end %>
		  </tbody>
		</table>
	</div>
</div>

app/views/layouts/_menu.html.erb
<% if user_signed_in? -%>
	<nav class="top-bar" data-topbar>
		<ul class="title-area">
			<li class="name">
				<h1><a href="/"><%= image_tag "logo.png" %>Coffee Capsules</a></h1>
			</li>
			<li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
		</ul>
		
		<section class="top-bar-section">
			<!-- Right Nav Section -->
			<ul class="right">
				<li class="divider"></li>
				<li><a href="#"><%= link_to current_user.login, "/users/edit" %></a></li>
				<li class="divider"></li>
				<li style="margin: 0px 15px; 0px 15px"><%= link_to 'Sign out', destroy_user_session_path, :method => :delete, :class => 'small button' %></li>
			</ul>
			<!-- Left Nav Section -->
			<ul class="left">
				<li class="divider"></li>
				<li class="has-dropdown">
					<a href="#">Capsule Types</a>
					<ul class="dropdown">
						<li><%= link_to 'List', :coffee_types %></li>
						<li><%= link_to 'New', new_coffee_type_path %></li>
					</ul>
				</li>
				<li class="divider"></li>
				<li class="has-dropdown">
					<a href="#">Appointments</a>
					<ul class="dropdown">
						<li><%= link_to 'List all', :appointments %></li>
						<li><%= link_to 'List my', "/appointments/by_user/current" %></li>
						<li><%= link_to 'New', new_appointment_path %></li>
					</ul>
				</li>
				<li class="divider"></li>
			</ul>
		</section>
	</nav>
<% end -%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Coffee Balance" %></title>

	<%= favicon_link_tag "favicon.ico" %>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

	<%= render "layouts/menu" %>
	<section role="main" class="scroll-container">
		<%= yield %>
	</section>
	
	<footer>
		<div class="row">
			<div class="large-12 large-centered columns">
				<div class="panel">
		  			<p>&copy; Coffee Capsules - by <a href="http://www.linkedin.com/profile/view?id=44607215" target="_blank">Rafael Berne</a></p>
				</div>
			</div>
		</div>
	</footer>
	
    <%= javascript_include_tag "application" %>
  </body>
  <script>
	$(document).ready(function() {
	  var $select = $("select.select2");
	  if ($select.length > 0) {
	  	$select.select2();
	  }
	  

      fixFooter();
	    $(window).bind("resize", function () {
	      fixFooter();
	  });
		
	  function fixFooter() {
        var footer = $("footer");
		var pos = footer.position();
		var height = $(window).height();
		height = height - pos.top;
		height = height - footer.height();
		if (height > 0) {
		  footer.css({ 'margin-top': height + 'px' });
		}
	  }
	});
  </script>
</html>